enum FailuresConstants {
    FAILURES_FETCHED = 'FAILURES_FETCHED',
    FAILURES_FILTERED = 'FAILURES_FILTERED',
    NODE_CHANGED = 'NODE_CHANGED',
    DATE_CHANGED = 'DATE_CHANGED',
    TREE_CHANGED = 'TREE_CHANGED',
    FAILURE_SELECTED = 'FAILURE_SELECTED',
    FAILURE_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
    FAILURE_WARNING_TYPE_FILTER = 'WARNING_TYPE_FILTER', // Недостоверные события
    FAILURES_INSERTED = 'FAILURES_INSERTED',
    FAILURE_UPDATED = 'FAILURE_UPDATED',
    FAILURE_TYPE_CHANGED = 'FAILURE_TYPE_CHANGED',
    FAILURE_CONSEQ_CHANGED = 'FAILURE_CONSEQ_CHANGED'
}

export default FailuresConstants;