enum EditorSiModelConstants {
    EDITORSIMODEL_FETCHED = 'EDITORSIMODEL_FETCHED',
    EDITORSIMODEL_FILTERED = 'EDITORSIMODEL_FILTERED',
    EDITORSIMODEL_UPDATED = 'EDITORSIMODEL_UPDATED',
    EDITORSIMODEL_INSERTED = 'EDITORSIMODEL_INSERTED',
    EDITORSIMODEL_ARCHIVE_FILTER = 'EDITORSIMODEL_ARCHIVE_FILTER',
}

export default EditorSiModelConstants;