export enum RecommendationsTypeModals {
    NEW_RECOMMENDATION_MODAL = "NEW_RECOMMENDATION_MODAL",
    EDIT_RECOMMENDATION_MODAL = "EDIT_RECOMMENDATION_MODAL",
    ORDER_RECOMMENDATION_MODAL = "ORDER_RECOMMENDATION_MODAL",
}