enum GroupEventSettingsConstants {
    GROUP_EVSETTINGS_FILLTABLE = 'CTRL_GROUP_EVENTSETTINGS_FILLTABLE',
    GROUP_EVSETTINGS_BTN_DISABLED = 'CTRL_GROUP_EVSETTINGS_BTN_DISABLED',
    GROUP_MAIL_CHECKED = 'CTRL_GROUP_MAIL_CHECKED',
    GROUP_WEB_CHECKED = 'CTRL_GROUP_WEB_CHECKED',
    CURRENT_GROUP = 'CTRL_CURRENT_GROUP',
    CTRL_RESET_GROUP_EVENTSETTINGS_INITIAL_VALUES = 'CTRL_RESET_GROUP_EVENTSETTINGS_INITIAL_VALUES',
}

export default GroupEventSettingsConstants;