enum EditorSiMapConstants {
    EDITORSIMAP_FETCHED = 'EDITORSIMAP_FETCHED',
    EDITORSIMAP_FILTERED = 'EDITORSIMAP_FILTERED',
    EDITORSIMAP_UPDATED = 'EDITORSIMAP_UPDATED',
    EDITORSIMAP_INSERTED = 'EDITORSIMAP_INSERTED',
    TREE_CHANGED = 'TREE_CHANGED',
    NODE_CHANGED = 'NDOE_CHANGED',
    ARCHIVE_FILTER = 'ARCHIVE_FILTER',
    EDITORSIMAP_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
}

export default EditorSiMapConstants;