enum DataSiConstants {
    DATASI_FETCHED = 'DATASI_FETCHED',
    DATASI_FILTERED = 'DATASI_FILTERED',
    DATASI_UPDATED = 'DATASI_UPDATED',
    DATASI_INSERTED = 'DATASI_INSERTED',
    TREE_CHANGED = 'TREE_CHANGED',
    NODE_CHANGED = 'NODE_CHANGED',
    ARCHIVE_FILTER = 'ARCHIVE_FILTER',
    DATASI_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
}

export default DataSiConstants;