enum GroupEventSettingsConstants {
    GROUP_EVSETTINGS_FILLTABLE = 'GROUP_EVENTSETTINGS_FILLTABLE',
    GROUP_EVSETTINGS_BTN_DISABLED = 'GROUP_EVSETTINGS_BTN_DISABLED',
    GROUP_SIKN_TREE_FETCHED = 'GROUP_SIKN_TREE_FETCHED',
    GROUP_SIKN_TREE_CHECKED = 'GROUP_SIKN_TREE_CHECKED',
    GROUP_MAIL_CHECKED = 'GROUP_MAIL_CHECKED',
    GROUP_WEB_CHECKED = 'GROUP_WEB_CHECKED',
    CURRENT_GROUP = 'CURRENT_GROUP',
    RESET_GROUP_EVENTSETTINGS_INITIAL_VALUES = 'RESET_GROUP_EVENTSETTINGS_INITIAL_VALUES',
}

export default GroupEventSettingsConstants;