enum ItemsConstants {
    ITEMS_FETCH_START = 'FETCH_START',
    ITEM_INSERT_START = 'INSERT_START',
    ITEM_UPDATE_START = 'UPDATE_START',
    ITEM_DELETE_START = 'DELETE_START',
    ITEMS_FETCH_ERROR = 'FETCH_ERROR',
    ITEM_INSERT_ERROR = 'INSERT_ERROR',
    ITEM_UPDATE_ERROR = 'UPDATE_ERROR',
    ITEM_DELETE_ERROR = 'DELETE_ERROR',
    ITEMS_FETCHED = 'FETCHED',
    ITEM_INSERTED = 'INSERTED',
    ITEM_UPDATED = 'UPDATED',
    ITEM_DELETED = 'DELETED',
    ITEM_SELECTED = 'SELECTED',
    ITEM_INSERT_FAIL = 'INSERT_FAIL',
    ITEM_UPDATE_FAIL = 'UPDATE_FAIL',
    ITEM_DELETE_FAIL = 'DELETE_FAIL',
}

export default ItemsConstants;