enum SiknOffConstants {
    OFFS_FETCHED = 'SIKNOFFS_FETCHED',
    OFF_UPDATED = 'SIKNOFF_UPDATED',
    OFF_INSERTED = 'SIKNOFF_INSERTED',
    OFFS_FILTERED = 'SIKNOFFS_FILTERED',
    RSU_FILTER = 'RSU_FILTER',
    REPORT_FILTER = 'REPORT_FILTER',
    NODE_CHANGED = 'SO_NODE_CHANGED',
    DATE_CHANGED = 'DATE_CHANGED',
    OFF_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
}

export default SiknOffConstants;