enum EventSettingsConstants {
    EVSETTINGS_FILLTABLE = 'EVENTSETTINGS_FILLTABLE',
    EVSETTINGS_BTN_DISABLED = 'EVSETTINGS_BTN_DISABLED',
    EVSETTINGS_RESET_BTN_DISABLED = 'EVSETTINGS_RESET_BTN_DISABLED',
    SIKN_TREE_FETCHED = 'SIKN_TREE_FETCHED',
    SIKN_TREE_CHECKED = 'SIKN_TREE_CHECKED',
    MAIL_CHECKED = 'MAIL_CHECKED',
    WEB_CHECKED = 'WEB_CHECKED',
    RESET_TO_ADMIN = 'EVENTSETTINGS_RESET_TO_ADMIN',
    RESET_EVENTSETTINGS_INITIAL_VALUES = 'RESET_EVENTSETTINGS_INITIAL_VALUES',
}

export default EventSettingsConstants;