enum EditorSiEquipmentConstants {
    EDITORSIEQ_FETCHED = 'EDITORSIEQ_FETCHED',
    EDITORSIEQ_FILTERED = 'EDITORSIEQ_FILTERED',
    EDITORSIEQ_UPDATED = 'EDITORSIEQ_UPDATED',
    EDITORSIEQ_INSERTED = 'EDITORSIEQ_INSERTED',
    TREE_CHANGED = 'TREE_CHANGED',
    NODE_CHANGED = 'NODE_CHANGED',
    EDITORSIEQ_ARCHIVE_FILTER = 'EDITORSIEQ_ARCHIVE_FILTER',
    EDITORSIEQ_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
}

export default EditorSiEquipmentConstants;