enum ToKmhConstants {
  TOKMH_FETCHED = "TOKMH_FETCHED",
  TOKMH_FILTERED = "TOKMH_FILTERED",
  /*  NODE_CHANGED = 'TOKMH_NODE_CHANGED',
    DATE_CHANGED = 'TOKMH_DATE_CHANGED',
    TREE_CHANGED = 'TOKMH_TREE_CHANGED', 
    TOKMH_OWNED_TYPE_FILTER = 'TOKMH_OWNED_TYPE_FILTER',*/
  TOKMH_UPDATED = "TOKMH_UPDATED",

  NODE_CHANGED = "TOKMX_NODE_CHANGED",
  DATE_CHANGED = "DATE_CHANGED",
  TREE_CHANGED = "TOKMX_TREE_CHANGED",
  TOKMH_OWNED_TYPE_FILTER = "OWNED_TYPE_FILTER",
}

export default ToKmhConstants;
