export enum MeasRangeConstants {
    MEASRANGE_FETCHED = 'MEASRANGE_FETCHED',
    MEASRANGE_FILTERED = 'MEASRANGE_FILTERED',
    MEASRANGE_UPDATED = 'MEASRANGE_UPDATED',
    MEASRANGE_INSERTED = 'MEASRANGE_INSERTED',
    TREE_CHANGED = 'TREE_CHANGED',
    NODE_CHANGED = 'NODE_CHANGED',
    MEASRANGE_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
}

// export default MeasRangeConstants;
