export enum ViolationActModals {
  NEW_VIOLATION_MODAL = "NEW_VIOLATION_MODAL",
  NEW_VIOLATION_FROM_DIR_MODAL = "NEW_VIOLATION_FROM_DIR_MODAL",
  TYPICAL_VIOLATION_MODAL = "TYPICAL_VIOLATION_MODAL",
  NEW_TYPICAL_VIOLATION_MODAL = "NEW_TYPICAL_VIOLATION_MODAL",
  TYPICAL_VIOLATION_MODAL_FROM_DIR = "TYPICAL_VIOLATION_MODAL_FROM_DIR",
  EDIT_NEW_VIOLATION_MODAL = "EDIT_NEW_VIOLATION_MODAL",
  EDIT_TYPICAL_VIOLATION_MODAL = "EDIT_TYPICAL_VIOLATION_MODAL",
  COPY_VIOLATION_MODAL = "COPY_VIOLATION_MODAL",
  CHANGE_VIOLATION_ORDER_MODAL = "CHANGE_VIOLATION_ORDER_MODAL",
  CHANGE_AREA_VIOLATION_ORDER_MODAL = "CHANGE_AREA_VIOLATION_ORDER_MODAL"
}
