enum CtrlEventSettingsConstants {
    EVSETTINGS_FILLTABLE = 'CTRL_EVENTSETTINGS_FILLTABLE',
    EVSETTINGS_BTN_DISABLED = 'CTRL_EVSETTINGS_BTN_DISABLED',
    EVSETTINGS_RESET_BTN_DISABLED = 'CTRL_EVSETTINGS_RESET_BTN_DISABLED',
    MAIL_CHECKED = 'CTRL_MAIL_CHECKED',
    WEB_CHECKED = 'CTRL_WEB_CHECKED',
    RESET_TO_ADMIN = 'CTRL_EVENTSETTINGS_RESET_TO_ADMIN',
    CTRL_RESET_EVENTSETTINGS_INITIAL_VALUES = 'CTRL_RESET_EVENTSETTINGS_INITIAL_VALUES',
}

export default CtrlEventSettingsConstants;