export enum FileFormats {
  txt = "text", // Text
  image = "image", // Image
  pdf = "application/pdf", // PDF
  json = "application/json", // JSON
  xml = "application/xml", // XML
  doc = "application/msword",
  dot = "application/msword",
  docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  dotx = "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
  docm = "application/vnd.ms-word.document.macroEnabled.12",
  dotm = "application/vnd.ms-word.template.macroEnabled.12",
  xls = "application/vnd.ms-excel",
  xlt = "application/vnd.ms-excel",
  xla = "application/vnd.ms-excel",
  xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xltx = "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
  xlsm = "application/vnd.ms-excel.sheet.macroEnabled.12",
  xltm = "application/vnd.ms-excel.template.macroEnabled.12",
  xlam = "application/vnd.ms-excel.addin.macroEnabled.12",
  xlsb = "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
  ppt = "application/vnd.ms-powerpoint",
  pot = "application/vnd.ms-powerpoint",
  pps = "application/vnd.ms-powerpoint",
  ppa = "application/vnd.ms-powerpoint",
  pptx = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  potx = "application/vnd.openxmlformats-officedocument.presentationml.template",
  ppsx = "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
  ppam = "application/vnd.ms-powerpoint.addin.macroEnabled.12",
  pptm = "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
  potm = "application/vnd.ms-powerpoint.template.macroEnabled.12",
  ppsm = "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
  mdb = "application/vnd.ms-access",
}

export const AllowedTextFileFormats = [
  FileFormats.txt,
  FileFormats.image,
  FileFormats.pdf,
  FileFormats.json,
  FileFormats.xml,
  FileFormats.doc,
  FileFormats.dot,
  FileFormats.docx,
  FileFormats.dotx,
  FileFormats.docm,
  FileFormats.dotm,
  FileFormats.xls,
  FileFormats.xlt,
  FileFormats.xla,
  FileFormats.xlsx,
  FileFormats.xltx,
  FileFormats.xlsm,
  FileFormats.xltm,
  FileFormats.xlam,
  FileFormats.xlsb,
  FileFormats.ppt,
  FileFormats.pot,
  FileFormats.pps,
  FileFormats.ppa,
  FileFormats.pptx,
  FileFormats.potx,
  FileFormats.ppsx,
  FileFormats.ppam,
  FileFormats.pptm,
  FileFormats.potm,
  FileFormats.ppsm,
  FileFormats.mdb,
];

export enum FileExtensions {
  // Images
  jpg = "jpg",
  jpeg = "jpeg",
  png = "png",
  svg = "svg",
  bmp = "bmp",

  txt = "txt",
  image = "image",
  pdf = "pdf",
  json = "json",
  xml = "xml",
  doc = "doc",
  dot = "dot",
  docx = "docx",
  dotx = "dotx",
  docm = "docm",
  dotm = "dotm",
  xls = "xls",
  xlt = "xlt",
  xla = "xla",
  xlsx = "xlsx",
  xltx = "xltx",
  xlsm = "xlsm",
  xltm = "xltm",
  xlam = "xlam",
  xlsb = "xlsb",
  ppt = "ppt",
  pot = "pot",
  pps = "pps",
  ppa = "ppa",
  pptx = "pptx",
  potx = "potx",
  ppsx = "ppsx",
  ppam = "ppam",
  pptm = "pptm",
  potm = "potm",
  ppsm = "ppsm",
  mdb = "mdb",
}

export const AllowedTextFileExtensions = [
  FileExtensions.jpg,
  FileExtensions.jpeg,
  FileExtensions.png,
  FileExtensions.svg,
  FileExtensions.bmp,
  FileExtensions.txt,
  FileExtensions.image,
  FileExtensions.pdf,
  FileExtensions.json,
  FileExtensions.xml,
  FileExtensions.doc,
  FileExtensions.dot,
  FileExtensions.docx,
  FileExtensions.dotx,
  FileExtensions.docm,
  FileExtensions.dotm,
  FileExtensions.xls,
  FileExtensions.xlt,
  FileExtensions.xla,
  FileExtensions.xlsx,
  FileExtensions.xltx,
  FileExtensions.xlsm,
  FileExtensions.xltm,
  FileExtensions.xlam,
  FileExtensions.xlsb,
  FileExtensions.ppt,
  FileExtensions.pot,
  FileExtensions.pps,
  FileExtensions.ppa,
  FileExtensions.pptx,
  FileExtensions.potx,
  FileExtensions.ppsx,
  FileExtensions.ppam,
  FileExtensions.pptm,
  FileExtensions.potm,
  FileExtensions.ppsm,
  FileExtensions.mdb,
];

export const MainAttachmentErrorMessage =
  'Установите признак "Основной" у одного из вложений';

export const ActionPlanErrorMessage =
  "У нарушений отсутствуют планы мероприятий";
