enum EventsConstants {
    EVENTS_FETCHED = 'EVENTS_FETCHED',
    EVENTS_FILTERED = 'EVENTS_FILTERED',
    NODE_CHANGED = 'NODE_CHANGED',
    DATE_CHANGED = 'DATE_CHANGED',
    TREE_CHANGED = 'TREE_CHANGED',
    EVENT_SELECTED = 'EVENT_SELECTED',
    EVENT_LEVEL_FILTER = 'EVENT_LEVEL_FILTER',
    EVENT_OWNED_TYPE_FILTER = 'OWNED_TYPE_FILTER',
    EVENT_WARNING_TYPE_FILTER = 'EVENT_WARNING_TYPE_FILTER', // Недостоверные события
    EVENT_TYPE_CHANGED = 'EVENT_TYPE_CHANGED'
}

export default EventsConstants;