export const FilterConfig = {
    filterGroupList: [
        {
            name: 'group1',
            propName: 'group1',
            filterList: [
                {
                    name: 'Наименование ПСП1',
                    propName: 'PspFullName1',
                    orderPropName: 'OstRnu.PspFullName1',
                    typeField: 'input',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП2',
                    propName: 'PspFullName2',
                    orderPropName: 'OstRnu.PspFullName2',
                    typeField: 'input',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП3',
                    propName: 'PspFullName3',
                    orderPropName: 'OstRnu.PspFullName3',
                    typeField: 'input',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП6',
                    propName: 'PspFullName6',
                    orderPropName: 'OstRnu.PspFullName6',
                    typeField: 'textarea',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП4',
                    propName: 'PspFullName4',
                    orderPropName: 'OstRnu.PspFullName4',
                    typeField: 'input',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП5',
                    propName: 'PspFullName5',
                    orderPropName: 'OstRnu.PspFullName5',
                    typeField: 'textarea',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП7',
                    propName: 'PspFullName7',
                    orderPropName: 'OstRnu.PspFullName7',
                    typeField: 'checkbox',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП8',
                    propName: 'PspFullName8',
                    orderPropName: 'OstRnu.PspFullName8',
                    typeField: 'checkbox',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
                {
                    name: 'Наименование ПСП9',
                    propName: 'PspFullName9',
                    orderPropName: 'OstRnu.PspFullName9',
                    typeField: 'checkbox',
                    type: 'String',
                    controller: 'pspcontrol/filters/psps',
                },
            ],
        },
    ],
};
